# Generated by Django 4.2.3 on 2023-07-27 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisement',
            table='Advertisement',
        ),
    ]
