# Generated by Django 4.2.3 on 2023-08-03 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_alter_advertisement_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisement',
            table='Advertisement',
        ),
    ]
